name: Create / Edit Release
on:
  release:
    types: [ published, created, edited ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Release SBOMs
        uses: anchore/sbom-action/publish-sbom@v0
